# Generated by Django 6.0.6 on 2026-06-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docchat', '0002_chatsession_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='Role',
            new_name='role',
        ),
    ]
