# Generated by Django 6.0.6 on 2026-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docchat', '0003_rename_role_chatmessage_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='context',
            new_name='content',
        ),
    ]
