# Generated by Django 6.0.6 on 2026-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docchat', '0005_chatsession_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='documents',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
