input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [logger_name] =~ /celery/ or [logger_name] =~ /Docchat\.tasks/ {
    mutate { add_tag => ["celery"] }
  }

  if [logger_name] =~ /consumers/ {
    mutate { add_tag => ["websocket"] }
  }

  if [logger_name] =~ /Docchat\.services/ {
    mutate { add_tag => ["rag"] }
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docuquery-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_verification_mode => none
  }
}
